Add R-MAT model
gmum/huggingmolecules pull request #20
Opened 2021-10-15 11:57 UTC by panpiort8

solves #17

2021-11-02 08:14 UTC, kudkudak commented
Mergujemy? :)

2021-11-02 08:17 UTC, Mazzza commented
Dzisiaj to ogarnę. Dzięki za przypomnienie :)

W dniu wt., 2.11.2021 o 09:15 Stanislaw Jastrzebski <
***@***.***> napisał(a):

> Mergujemy? :)
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/gmum/huggingmolecules/pull/20#issuecomment-957190176>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACC4SA7AGVW6TAO4P77H4HTUJ6MYZANCNFSM5GBZ4EBQ>
> .
>
>
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2022-02-28 11:10 UTC, panpiort8 commented
@Mazzza maybe today is a good day?

2022-03-21 10:33 UTC, Mazzza requested changes

2022-03-21 10:33 UTC, Mazzza commented on src/huggingmolecules/configuration/configuration_rmat.py
> +    init_type: str = 'normal'
there was uniform in original code, but i think its marginal thing

2022-03-21 10:33 UTC, Mazzza commented on src/huggingmolecules/configuration/configuration_rmat.py
> +    generator_aggregation: str = 'mean'
we used attention pooling, not mean

2022-03-21 10:33 UTC, Mazzza commented on src/huggingmolecules/configuration/configuration_rmat.py
> +    generator_features_generators: List[str] = None
i think, that we could also do another config for rmat with rdkit features, as there are slightly different hps for generator

2022-05-07 13:56 UTC, panpiort8 commented on src/huggingmolecules/configuration/configuration_rmat.py
> +    init_type: str = 'normal'
done

2022-05-07 13:56 UTC, panpiort8 commented on src/huggingmolecules/configuration/configuration_rmat.py
> +    generator_aggregation: str = 'mean'
done

2022-05-07 13:57 UTC, panpiort8 commented on src/huggingmolecules/configuration/configuration_rmat.py
> +    generator_features_generators: List[str] = None
done

2022-05-07 13:58 UTC, merged